# Generated by Django 5.0.6 on 2024-06-11 07:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator(code='invalid_alphabets', message='Only alphabetic characters are allowed.', regex='^[a-zA-Z]+$')])),
                ('last_name', models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator(code='invalid_alphabets', message='Only alphabetic characters are allowed.', regex='^[a-zA-Z]+$')])),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('token_expiration', models.DateTimeField(blank=True, null=True)),
                ('last_logout', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageBlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=255)),
                ('state_id', models.CharField(max_length=10)),
                ('place_name', models.CharField(max_length=255)),
                ('place_id', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('blog', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place1',
            fields=[
                ('placeid', models.AutoField(primary_key=True, serialize=False)),
                ('stateid', models.CharField(blank=True, max_length=2, null=True)),
                ('placename', models.CharField(max_length=255)),
                ('placedetails', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'place',
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=50)),
                ('famousfor', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'india',
            },
        ),
        migrations.CreateModel(
            name='Place2',
            fields=[
                ('placeid', models.AutoField(primary_key=True, serialize=False)),
                ('placename', models.CharField(max_length=255)),
                ('placedetails', models.CharField(max_length=255)),
                ('stateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.states')),
            ],
        ),
    ]
