# Generated by Django 5.0.6 on 2024-06-17 05:55

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator(code='invalid_alphabets', message='Only alphabetic characters are allowed.', regex='^[a-zA-Z]+$')])),
                ('last_name', models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator(code='invalid_alphabets', message='Only alphabetic characters are allowed.', regex='^[a-zA-Z]+$')])),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('token_expiration', models.DateTimeField(blank=True, null=True)),
                ('last_logout', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageBlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=255)),
                ('state_id', models.CharField(max_length=10)),
                ('place_name', models.CharField(max_length=255)),
                ('place_id', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('blog', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
