# Generated by Django 5.0.6 on 2024-05-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_userregistration_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='username',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
