# Generated by Django 5.0.6 on 2024-05-26 03:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_remove_userregistration_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='first_name',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator(code='invalid_alphabets', message='Only alphabetic characters are allowed.', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='last_name',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator(code='invalid_alphabets', message='Only alphabetic characters are allowed.', regex='^[a-zA-Z]+$')]),
        ),
    ]
