# Generated by Django 5.0.6 on 2024-06-24 17:00

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('userId', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('firstName', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(code='invalid_alphabets', message='Only alphabetic characters are allowed.', regex='^[a-zA-Z]+$')])),
                ('lastName', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(code='invalid_alphabets', message='Only alphabetic characters are allowed.', regex='^[a-zA-Z]+$')])),
                ('userName', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('joinDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastloginDate', models.DateTimeField(blank=True, null=True)),
                ('lastlogoutDate', models.DateTimeField(blank=True, null=True)),
                ('jwtToken', models.TextField(blank=True, null=True)),
                ('jwtExpTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
