# Generated by Django 5.0.6 on 2024-06-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trvexp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='userName',
            field=models.CharField(max_length=255),
        ),
    ]
