# Generated by Django 5.0.6 on 2024-06-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trvexp', '0002_alter_usertable_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
